# Generated by Django 4.2.20 on 2025-04-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("other_app", "0002_customprogram"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomProgram",
        ),
    ]
