# Generated by Django 4.2.20 on 2025-04-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("other_app", "0003_delete_customprogram"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("link", models.URLField(verbose_name="Ссылка")),
            ],
            options={
                "verbose_name": "Ссылка на соц. сеть",
                "verbose_name_plural": "Ссылки на соц. сети",
            },
        ),
    ]
