# Generated by Django 4.2.20 on 2025-04-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("other_app", "0004_sociallinks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessmatrixmodel",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="messagesupport",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="privacypolicy",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="publicofferagreement",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
    ]
