# Generated by Django 4.2.20 on 2025-04-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("other_app", "0006_fix_token_jti_hex"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessmatrixmodel",
            name="price",
            field=models.PositiveIntegerField(default=0, verbose_name="Стоимость"),
        ),
    ]
