# Generated by Django 4.2.20 on 2025-03-16 12:47

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskpersonalarcana1",
            name="description",
            field=ckeditor.fields.RichTextField(
                help_text="Описание задачи для персонального аркана1 (t)",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="taskpersonalarcana1",
            name="title",
            field=models.CharField(
                help_text="Задача для персонального аркана1 (t)",
                max_length=255,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="taskpersonalarcana2",
            name="description",
            field=ckeditor.fields.RichTextField(
                help_text="Описание задачи для персонального аркана2 (u)",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="taskpersonalarcana2",
            name="title",
            field=models.CharField(
                help_text="Задача для персонального аркана2 (u)",
                max_length=255,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="taskpersonalarcana3",
            name="description",
            field=ckeditor.fields.RichTextField(
                help_text="Описание задачи для персонального аркана1 (v)",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="taskpersonalarcana3",
            name="title",
            field=models.CharField(
                help_text="Задача для персонального аркана1 (v)",
                max_length=255,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="tasksopenmoneychannel1",
            name="description",
            field=ckeditor.fields.RichTextField(
                help_text="Какие нужно проработать задачи, чтобы раскрыть денежный канал: (l)",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="tasksopenmoneychannel1",
            name="title",
            field=models.CharField(
                help_text="Какие нужно проработать задачи, чтобы раскрыть денежный канал: (l)",
                max_length=255,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="whatblocksmoneyenergy",
            name="description",
            field=ckeditor.fields.RichTextField(
                help_text="Что блокирует денежную энергию: (j)", verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="whatblocksmoneyenergy",
            name="title",
            field=models.CharField(
                help_text="Что блокирует денежную энергию: (j)",
                max_length=255,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="whatopensyourmoneychannel",
            name="description",
            field=ckeditor.fields.RichTextField(
                help_text="Что открывает ваш денежный канал (l)",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="whatopensyourmoneychannel",
            name="title",
            field=models.CharField(
                help_text="Что открывает ваш денежный канал (l)",
                max_length=255,
                verbose_name="Название",
            ),
        ),
        migrations.CreateModel(
            name="WhatBeforeYouTurn40Years",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Что нужно сделать до 40 лет: (c1)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Что нужно сделать до 40 лет: (c1)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="what_before_you_turn_40_years",
                        to="finance_app.financecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Что нужно сделать до 40 лет",
                "verbose_name_plural": "Что нужно сделать до 40 лет",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="WhatAfterYouTurn40Years",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Что нужно сделать после 40 лет: (c2)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Что нужно сделать после 40 лет: (c2)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="what_after_you_turn_40_years",
                        to="finance_app.financecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Что нужно сделать после 40 лет",
                "verbose_name_plural": "Что нужно сделать после 40 лет",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="TheMainTask40Years",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Главная задача 40 лет (c)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Главная задача 40 лет (c)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="the_main_task_40_years",
                        to="finance_app.financecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Главная задача 40 лет",
                "verbose_name_plural": "Главные задачи 40 лет",
                "unique_together": {("category", "order_id")},
            },
        ),
    ]
