# Generated by Django 4.2.20 on 2025-03-24 17:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0002_alter_taskpersonalarcana1_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatrixFinanceProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название программы"),
                ),
                (
                    "marker_1_name",
                    models.CharField(
                        help_text="Пример: a, a1, a2",
                        max_length=3,
                        verbose_name="Маркер 1",
                    ),
                ),
                (
                    "marker_1_value",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                            (13, 13),
                            (14, 14),
                            (15, 15),
                            (16, 16),
                            (17, 17),
                            (18, 18),
                            (19, 19),
                            (20, 20),
                            (21, 21),
                            (22, 22),
                        ],
                        help_text="Значение от 1 до 22",
                        verbose_name="Значение маркера 1",
                    ),
                ),
                (
                    "marker_2_name",
                    models.CharField(
                        help_text="Пример: b, b1, b2",
                        max_length=3,
                        verbose_name="Маркер 2",
                    ),
                ),
                (
                    "marker_2_value",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                            (13, 13),
                            (14, 14),
                            (15, 15),
                            (16, 16),
                            (17, 17),
                            (18, 18),
                            (19, 19),
                            (20, 20),
                            (21, 21),
                            (22, 22),
                        ],
                        help_text="Значение от 1 до 22",
                        verbose_name="Значение маркера 2",
                    ),
                ),
                (
                    "marker_3_name",
                    models.CharField(
                        help_text="Пример: m, n, c2",
                        max_length=3,
                        verbose_name="Маркер 3",
                    ),
                ),
                (
                    "marker_3_value",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                            (13, 13),
                            (14, 14),
                            (15, 15),
                            (16, 16),
                            (17, 17),
                            (18, 18),
                            (19, 19),
                            (20, 20),
                            (21, 21),
                            (22, 22),
                        ],
                        help_text="Значение от 1 до 22",
                        verbose_name="Значение маркера 3",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True, verbose_name="Описание программы"
                    ),
                ),
            ],
        ),
    ]
