# Generated by Django 4.2.20 on 2025-04-03 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0003_matrixfinanceprogram"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matrixfinanceprogram",
            options={
                "verbose_name": "Программа Финансы",
                "verbose_name_plural": "Программы Финансы",
            },
        ),
        migrations.AddField(
            model_name="areasofrealization",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="qualitiesdevelopage40",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="qualitiesrevealedage20",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="taskpersonalarcana1",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="taskpersonalarcana2",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="taskpersonalarcana3",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="tasksopenmoneychannel1",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="tasksopenmoneychannel2",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="themaintask40years",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="whatafteryouturn40years",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="whatbeforeyouturn40years",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="whatblocksmoneyenergy",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="whatgivesyoumoney",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="whatopensyourmoneychannel",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="yourgreatesttalentbirth",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="youropportunity",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AlterField(
            model_name="areasofrealization",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="qualitiesdevelopage40",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="qualitiesrevealedage20",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="taskpersonalarcana1",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="taskpersonalarcana2",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="taskpersonalarcana3",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="tasksopenmoneychannel1",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="tasksopenmoneychannel2",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="themaintask40years",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="whatafteryouturn40years",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="whatbeforeyouturn40years",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="whatblocksmoneyenergy",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="whatgivesyoumoney",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="whatopensyourmoneychannel",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="yourgreatesttalentbirth",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="youropportunity",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
    ]
