# Generated by Django 4.2.20 on 2025-05-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0004_alter_matrixfinanceprogram_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="matrixfinanceprogram",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
