# Generated by Django 4.2.20 on 2025-03-16 06:55

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChildCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Название категории",
                        max_length=255,
                        verbose_name="Название категории",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание категории",
                        verbose_name="Описание категории",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(
                        default=False, verbose_name="Платная категория"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="WhatShouldComeQualitiesChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="К чему должны прийти, какие качества необходимо наработать ребенку: (a1)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="К чему должны прийти, какие качества необходимо наработать ребенку: (a1)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="what_should_come_qualities_child",
                        to="child_app.childcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "К чему должны прийти, какие качества необходимо наработать ребенку",
                "verbose_name_plural": "К чему должны прийти, какие качества необходимо наработать ребенку",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="WhatMistakesRelationshipParentsChildren",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Какие могут быть ошибки во взаимоотношениях с родителями и своими детьми:(a2)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Какие могут быть ошибки во взаимоотношениях с родителями и своими детьми:(a2)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="what_mistakes_relationship_parents_children",
                        to="child_app.childcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Какие могут быть ошибки во взаимоотношениях с родителями и своими детьми",
                "verbose_name_plural": "Какие могут быть ошибки во взаимоотношениях с родителями и своими детьми",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="WhatChildShouldTeachParents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Чему ребенок должен научить своих родителей: (a)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Чему ребенок должен научить своих родителей: (a)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="what_child_should_teach_parents",
                        to="child_app.childcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чему ребенок должен научить своих родителей",
                "verbose_name_plural": "Чему ребенок должен научить своих родителей",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="ThirdTalentRevealedAge40",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Третий талант раскрывается к 40 годам (c)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Третий талант раскрывается к 40 годам (c)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="third_talent_revealed_age_40",
                        to="child_app.childcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Третий талант раскрывается к 40 годам",
                "verbose_name_plural": "Третий талант раскрывается к 40 годам",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="SoulPastExperiencesWithPeople",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Опыт души в прошлом с людьми (d2)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Опыт души в прошлом с людьми (d2)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soul_past_experiences_with_people",
                        to="child_app.childcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опыт души в прошлом с людьми",
                "verbose_name_plural": "Опыт души в прошлом с людьми",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="QualitiesRevealedAgeOf20",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Качества которые раскрываются к 20 годам (b)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Качества которые раскрываются к 20 годам (b)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualities_revealed_age_of_20",
                        to="child_app.childcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Качества которые раскрываются к 20 годам",
                "verbose_name_plural": "Качества которые раскрываются к 20 годам",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="MainTaskSoul",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Главная задача Души (d)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Главная задача Души (d)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_task_soul",
                        to="child_app.childcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Главная задача Души",
                "verbose_name_plural": "Главная задача Души",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="LessonsFromPastLife",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Урок из прошлой жизни (d1)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Урок из прошлой жизни (d1)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons_from_past_life",
                        to="child_app.childcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок из прошлой жизни",
                "verbose_name_plural": "Урок из прошлой жизни",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="ChildPointOfComfort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Аркан точки душевного комфорта ребенка: (e)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Аркан точки душевного комфорта ребенка: (e)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_point_of_comfort",
                        to="child_app.childcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аркан точки душевного комфорта ребенка",
                "verbose_name_plural": "Аркан точки душевного комфорта ребенка",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="ChildOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Возможность ребенка: (a2)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Возможность ребенка: (a2)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_opportunity",
                        to="child_app.childcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Возможность ребенка",
                "verbose_name_plural": "Возможность ребенка",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="ChildDestinyArcana3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Предназначение ребенка (y)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Предназначение ребенка (y)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_destiny_arcana3",
                        to="child_app.childcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предназначение ребенка",
                "verbose_name_plural": "Предназначение ребенка",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="ChildDestinyArcana2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Предназначение ребенка (s)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Предназначение ребенка (s)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_destiny_arcana2",
                        to="child_app.childcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предназначение ребенка",
                "verbose_name_plural": "Предназначение ребенка",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="ChildDestinyArcana1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Предназначение ребенка (r)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Предназначение ребенка (r)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_destiny_arcana1",
                        to="child_app.childcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предназначение ребенка",
                "verbose_name_plural": "Предназначение ребенка",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="ChildBusinessCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Визитная карточка ребенка (a)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Визитная карточка ребенка (a)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_business_card",
                        to="child_app.childcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Визитная карточка ребенка (a)",
                "verbose_name_plural": "Визитная карточка ребенка (a)",
                "unique_together": {("category", "order_id")},
            },
        ),
    ]
