# Generated by Django 4.2.20 on 2025-04-03 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("child_app", "0002_matrixchildprogram"),
    ]

    operations = [
        migrations.AddField(
            model_name="childbusinesscard",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="childdestinyarcana1",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="childdestinyarcana2",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="childdestinyarcana3",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="childopportunity",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="childpointofcomfort",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="lessonsfrompastlife",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="maintasksoul",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="qualitiesrevealedageof20",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="soulpastexperienceswithpeople",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="thirdtalentrevealedage40",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="whatchildshouldteachparents",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="whatmistakesrelationshipparentschildren",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="whatshouldcomequalitieschild",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AlterField(
            model_name="childbusinesscard",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="childdestinyarcana1",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="childdestinyarcana2",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="childdestinyarcana3",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="childopportunity",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="childpointofcomfort",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="lessonsfrompastlife",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="maintasksoul",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="qualitiesrevealedageof20",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="soulpastexperienceswithpeople",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="thirdtalentrevealedage40",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="whatchildshouldteachparents",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="whatmistakesrelationshipparentschildren",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="whatshouldcomequalitieschild",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
    ]
