# Generated by Django 4.2.20 on 2025-05-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "child_app",
            "0003_childbusinesscard_marker_childdestinyarcana1_marker_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="matrixchildprogram",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
