# Generated by Django 4.2.20 on 2025-03-18 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matrix_auth_app", "0002_usercalculationhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercalculationhistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="usercalculationhistory",
            name="input_data",
            field=models.JSONField(verbose_name="Входные данные"),
        ),
        migrations.AlterField(
            model_name="usercalculationhistory",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calculations",
                to="matrix_auth_app.profile",
                verbose_name="Профиль",
            ),
        ),
        migrations.AlterField(
            model_name="usercalculationhistory",
            name="result_data",
            field=models.JSONField(verbose_name="Результат расчета"),
        ),
    ]
