# Generated by Django 4.2.20 on 2025-03-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matrix_auth_app", "0003_alter_usercalculationhistory_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercalculationhistory",
            name="category",
            field=models.CharField(
                choices=[
                    ("matrix_fate", "Калькулятор Матрица судьбы"),
                    ("finance", "Калькулятор Финансы"),
                    ("compatibility", "Калькулятор Совместимость"),
                    ("child", "Калькулятор Детская матрица"),
                ],
                default="matrix_fate",
                max_length=20,
                verbose_name="Раздел",
            ),
        ),
    ]
