# Generated by Django 4.2.20 on 2025-05-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matrix_auth_app", "0003_usercalculationhistory_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercalculationhistory",
            name="category",
            field=models.CharField(
                choices=[
                    ("matrix_fate", "Kohtalomatriisi laskin"),
                    ("finance", "Talouslaskin"),
                    ("compatibility", "Yhteensopivuuslaskin"),
                    ("child", "Lasten matriisi laskin"),
                ],
                default="matrix_fate",
                max_length=20,
                verbose_name="Раздел",
            ),
        ),
    ]
