# Generated by Django 4.2.20 on 2025-03-18 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matrix_auth_app", "0004_usercalculationhistory_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="access_expiration",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания доступа"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("level1", "Бесплатный"),
                    ("level2", "Разовый"),
                    ("level3", "Месячный"),
                    ("level4", "Годовой"),
                ],
                default="level1",
                max_length=20,
                verbose_name="Уровень доступа",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Аватар"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Полное имя"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
