# Generated by Django 4.2.20 on 2025-03-28 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matrix_auth_app", "0003_usercalculationhistory_category_and_more"),
        ("matrix_auth_app", "0005_alter_profile_access_expiration_and_more"),
    ]

    operations = []
