# Generated by Django 4.2.20 on 2025-03-16 10:31

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="April",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Апрель", max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Апрель", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
            ],
            options={
                "verbose_name": "Апрель",
                "verbose_name_plural": "Апрель",
            },
        ),
        migrations.CreateModel(
            name="August",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Август", max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Август", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
            ],
            options={
                "verbose_name": "Август",
                "verbose_name_plural": "Август",
            },
        ),
        migrations.CreateModel(
            name="December",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Декабрь", max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Декабрь", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
            ],
            options={
                "verbose_name": "Декабрь",
                "verbose_name_plural": "Декабрь",
            },
        ),
        migrations.CreateModel(
            name="February",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Февраль", max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Февраль", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
            ],
            options={
                "verbose_name": "Февраль",
                "verbose_name_plural": "Февраль",
            },
        ),
        migrations.CreateModel(
            name="GeneralPrognosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Общий прогноз",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Общий прогноз", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
            ],
            options={
                "verbose_name": "Общий прогноз",
                "verbose_name_plural": "Общий прогноз",
            },
        ),
        migrations.CreateModel(
            name="January",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Январь", max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Январь", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
            ],
            options={
                "verbose_name": "Январь",
                "verbose_name_plural": "Январь",
            },
        ),
        migrations.CreateModel(
            name="July",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Июль", max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Июль", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
            ],
            options={
                "verbose_name": "Июль",
                "verbose_name_plural": "Июль",
            },
        ),
        migrations.CreateModel(
            name="June",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Июнь", max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Июнь", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
            ],
            options={
                "verbose_name": "Июнь",
                "verbose_name_plural": "Июнь",
            },
        ),
        migrations.CreateModel(
            name="March",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Март", max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Март", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
            ],
            options={
                "verbose_name": "Март",
                "verbose_name_plural": "Март",
            },
        ),
        migrations.CreateModel(
            name="May",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Май", max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Май", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
            ],
            options={
                "verbose_name": "Май",
                "verbose_name_plural": "Май",
            },
        ),
        migrations.CreateModel(
            name="November",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Ноябрь", max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Ноябрь", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ноябрь",
                "verbose_name_plural": "Ноябрь",
            },
        ),
        migrations.CreateModel(
            name="October",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Октябрь", max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Октябрь", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
            ],
            options={
                "verbose_name": "Октябрь",
                "verbose_name_plural": "Октябрь",
            },
        ),
        migrations.CreateModel(
            name="September",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Сентябрь", max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Сентябрь", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сентябрь",
                "verbose_name_plural": "Сентябрь",
            },
        ),
    ]
