# Generated by Django 4.2.20 on 2025-03-13 16:04

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matrix_fate_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="birthtalent",
            options={
                "verbose_name": "Главный талант данный при рождении",
                "verbose_name_plural": "Главный талант данный при рождении",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="maturetalent",
            options={
                "verbose_name": "Третий талант нарабатывается к 40 годам",
                "verbose_name_plural": "Третий талант нарабатывается к 40 годам",
            },
        ),
        migrations.AlterModelOptions(
            name="youthtalent",
            options={
                "verbose_name": "Второй талант раскрывается к 20 годам",
                "verbose_name_plural": "Второй талант раскрывается к 20 годам",
            },
        ),
        migrations.CreateModel(
            name="TeachParents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Чему вы должны были научить своих родителей (a)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Чему вы должны были научить своих родителей (a)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teach_parents",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чему вы должны были научить родителей",
                "verbose_name_plural": "Чему вы должны были научить родителей",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="TaskBefore40",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Что нужно сделать до 40 лет",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Что нужно сделать до 40 лет", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_before_40",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача до 40 лет",
                "verbose_name_plural": "Задачи до 40 лет",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="TaskAfter40",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Что нужно сделать до 40 лет",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Что нужно сделать до 40 лет", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_after_40",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача до 40 лет",
                "verbose_name_plural": "Задачи до 40 лет",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="SuitableProfessions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Какие подходят профессии (c2)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Какие подходят профессии (c2)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suitable_professions",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Какие подходят профессии",
                "verbose_name_plural": "Какие подходят профессии",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="SuitablePartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Какой партнер вам подходит (k)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Какой партнер вам подходит (k)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suitable_partners",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подходящий партнер",
                "verbose_name_plural": "Подходящие партнеры",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="SpiritualTask3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Задача 3 (b2)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание задачи 3 (b2)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spiritual_task_3",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Духовная задача 3",
                "verbose_name_plural": "Духовные задачи 3",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="SpiritualTask2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Задача 2 (b1)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание задачи 2 (b1)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spiritual_task_2",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Духовная задача 2",
                "verbose_name_plural": "Духовные задачи 2",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="SpiritualTask1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Задача 1 (b)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание задачи 1 (b)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spiritual_task_1",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Духовная задача 1",
                "verbose_name_plural": "Духовные задачи 1",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="SpiritualPurpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Духовное предназначение (w)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Духовное предназначение (w)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spiritual_purpose",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Духовное предназначение",
                "verbose_name_plural": "Духовные предназначения",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="SoulMainTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Главная задача Души (d)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Главная задача Души (d)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soul_main_tasks",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Главная задача Души",
                "verbose_name_plural": "Главные задачи Души",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="SoulComfortPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Точка душевного комфорта (e)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Точка душевного комфорта (e)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soul_comfort_points",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Точка душевного комфорта",
                "verbose_name_plural": "Точки душевного комфорта",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="SocialPurpose3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Задача для социального 3 Аркана (v)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание задачи для социального 3 Аркана (v)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_purpose_3",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальная задача 3",
                "verbose_name_plural": "Социальные задачи 3",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="SocialPurpose2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Задача для социального 2 Аркана (u)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание задачи для социального 2 Аркана (u)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_purpose_2",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальная задача 2",
                "verbose_name_plural": "Социальные задачи 2",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="SocialPurpose1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Задача для социального 1 Аркана (t)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание задачи для социального 1 Аркана (t)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_purpose_1",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальная задача 1",
                "verbose_name_plural": "Социальные задачи 1",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="SelfRealization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Ваша возможность (a2)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Ваша возможность (a2)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="self_realizations",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Самореализация",
                "verbose_name_plural": "Самореализация",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="RelationshipProblems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Какие могут возникнуть проблемы в отношениях (j)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Какие могут возникнуть проблемы в отношениях (j)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationship_problems",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проблемы в отношениях",
                "verbose_name_plural": "Проблемы в отношениях",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="RelationshipMistakes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Ошибки во взаимоотношениях с родителями и детьми (a2)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Ошибки во взаимоотношениях с родителями и детьми (a2)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationship_mistakes",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ошибки в отношениях с родителями и детьми",
                "verbose_name_plural": "Ошибки в отношениях с родителями и детьми",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="QualitiesRevealed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Качества которые раскрываются к 20 годам (b)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Качества которые раскрываются к 20 годам (b)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualities_revealed",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Качества которые раскрываются к 20 годам",
                "verbose_name_plural": "Качества которые раскрываются к 20 годам",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="QualitiesDeveloped",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Качества которые нарабатываются к 40 годам (c)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Качества которые нарабатываются к 40 годам (c)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualities_developed",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Качества которые нарабатываются к 40 годам",
                "verbose_name_plural": "Качества которые нарабатываются к 40 годам",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="PersonalPurpose3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Задача для персонального 3 Аркана (y)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание задачи для персонального 3 Аркана (y)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_purpose_3",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персональная задача 3",
                "verbose_name_plural": "Персональные задачи 3",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="PersonalPurpose2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Задача для персонального 2 Аркана (s)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание задачи для персонального 2 Аркана (s)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_purpose_2",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персональная задача 2",
                "verbose_name_plural": "Персональные задачи 2",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="PersonalPurpose1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Задача для персонального 1 Аркана (r)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание задачи для персонального 1 Аркана (r)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_purpose_1",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персональная задача 1",
                "verbose_name_plural": "Персональные задачи 1",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="PersonalPowerPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Выполняйте рекомендации (e)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Выполняйте рекомендации (e)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_power_points",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Точка личной силы",
                "verbose_name_plural": "Точки личной силы",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="PersonalGrowth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="К чему должны прийти, какие качества необходимо в себе наработать (a1)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="К чему должны прийти, какие качества необходимо в себе наработать (a1)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_growth",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "К чему должны прийти",
                "verbose_name_plural": "К чему должны прийти",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="PaternalDiseases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Родовые заболевания по линии отца (h)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Родовые заболевания по линии отца (h)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paternal_diseases",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Родовое заболевание по линии отца",
                "verbose_name_plural": "Родовые заболевания по линии отца",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="PastLifeLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Урок из прошлой жизни (d1)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Урок из прошлой жизни (d1)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="past_life_lessons",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок из прошлой жизни",
                "verbose_name_plural": "Уроки из прошлой жизни",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="PastLifeExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Опыт вашей души в прошлом с людьми (d2)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Опыт вашей души в прошлом с людьми (d2)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="past_life_experiences",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опыт души в прошлом с людьми",
                "verbose_name_plural": "Опыт души в прошлом с людьми",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="PartnerTasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Какие задачи стоят с партнерами (d2)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Какие задачи стоят с партнерами (d2)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_tasks",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задачи с партнерами",
                "verbose_name_plural": "Задачи с партнерами",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="MoneyUnblock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Что помогает раскрыть деньги (j)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Что помогает раскрыть деньги (j)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_unblock",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Что помогает раскрыть деньги",
                "verbose_name_plural": "Что помогает раскрыть деньги",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="MoneySources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Что дает деньги (i1)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Что дает деньги (i1)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_sources",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Что дает деньги",
                "verbose_name_plural": "Что дает деньги",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="MoneyGrowthTasks2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Какие нужно проработать задачи, чтобы раскрыть денежный канал2(c2)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Какие нужно проработать задачи, чтобы раскрыть денежный канал2(c2)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_growth_tasks2",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача для денежного канала2",
                "verbose_name_plural": "Задачи для денежного канала2",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="MoneyGrowthTasks1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Какие нужно проработать задачи, чтобы раскрыть денежный канал1(i1)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Какие нужно проработать задачи, чтобы раскрыть денежный канал1(i1)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_growth_tasks1",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача для денежного канала1",
                "verbose_name_plural": "Задачи для денежного канала1",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="MoneyBlocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Что блокирует денежную энергию (j)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Что блокирует денежную энергию (j)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_blocks",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Что блокирует денежную энергию",
                "verbose_name_plural": "Что блокирует денежную энергию",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="MeetingPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Где можете познакомиться с партнером (k)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Где можете познакомиться с партнером (k)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_places",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Место знакомства с партнером",
                "verbose_name_plural": "Места знакомства с партнерами",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="MaternalDiseases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Родовые заболевания по линии матери (i)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Родовые заболевания по линии матери (i)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maternal_diseases",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Родовое заболевание по линии матери",
                "verbose_name_plural": "Родовые заболевания по линии матери",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="MainTask40",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Главная задача 40 лет (d)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Главная задача 40 лет (d)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_tasks_40",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Главная задача 40 лет",
                "verbose_name_plural": "Главные задачи 40 лет",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="InnateTalent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Ваш главный талант от рождения (a)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Ваш главный талант от рождения (a)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="innate_talents",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ваш главный талант от рождения",
                "verbose_name_plural": "Ваш главный талант от рождения",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="HealthMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Чакра и параметр",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание здоровья по чакре", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "chakra_type",
                    models.CharField(
                        choices=[
                            ("muladhara_o", "Муладхара_o"),
                            ("muladhara_p", "Муладхара_p"),
                            ("muladhara_q", "Муладхара_q"),
                            ("svadhisthana_o", "Свадхистана_o"),
                            ("svadhisthana_p", "Свадхистана_p"),
                            ("svadhisthana_q", "Свадхистана_q"),
                            ("manipura_o", "Манипура_o"),
                            ("manipura_p", "Манипура_p"),
                            ("manipura_q", "Манипура_q"),
                            ("anahata_o", "Анахата_o"),
                            ("anahata_p", "Анахата_p"),
                            ("anahata_q", "Анахата_q"),
                            ("vishuddha_o", "Вишудха_o"),
                            ("vishuddha_p", "Вишудха_p"),
                            ("vishuddha_q", "Вишудха_q"),
                            ("ajna_o", "Аджна_o"),
                            ("ajna_p", "Аджна_p"),
                            ("ajna_q", "Аджна_q"),
                            ("sahasrara_o", "Сахасрара_o"),
                            ("sahasrara_p", "Сахасрара_p"),
                            ("sahasrara_q", "Сахасрара_q"),
                            ("total_o", "Итого_o"),
                            ("total_p", "Итого_p"),
                            ("total_q", "Итого_q"),
                        ],
                        max_length=20,
                        verbose_name="Тип чакры",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_map",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья",
                "verbose_name_plural": "Карта здоровья",
                "unique_together": {("category", "order_id", "chakra_type")},
            },
        ),
        migrations.CreateModel(
            name="HealthArcane3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Предрасположенность к заболеваниям(c)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание предрасположенности к заболеваниям(c)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_arcane3",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предрасположенность к заболеваниям3",
                "verbose_name_plural": "Предрасположенности к заболеваниям3",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="HealthArcane2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Предрасположенность к заболеваниям(b)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание предрасположенности к заболеваниям(b)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_arcane2",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предрасположенность к заболеваниям2",
                "verbose_name_plural": "Предрасположенности к заболеваниям2",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="HealthArcane1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Предрасположенность к заболеваниям(a)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание предрасположенности к заболеваниям(a)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_arcane1",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предрасположенность к заболеваниям1",
                "verbose_name_plural": "Предрасположенности к заболеваниям1",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="AncestralTaskMotherMale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Задачи по мужской линии по роду матери (h)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание задач по мужской линии по роду матери (h)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ancestral_tasks_mother_male",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача по мужской линии матери",
                "verbose_name_plural": "Задачи по мужской линии матери",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="AncestralTaskMotherFemale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Задачи по женской линии по роду матери (i)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание задач по женской линии по роду матери (i)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ancestral_tasks_mother_female",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача по женской линии матери",
                "verbose_name_plural": "Задачи по женской линии матери",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="AncestralTaskFatherMale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Задачи по мужской линии по роду отца (f)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание задач по мужской линии по роду отца (f)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ancestral_tasks_father_male",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача по мужской линии отца",
                "verbose_name_plural": "Задачи по мужской линии отца",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="AncestralTaskFatherFemale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Задачи по женской линии по роду отца (g)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание задач по женской линии по роду отца (g)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ancestral_tasks_father_female",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача по женской линии отца",
                "verbose_name_plural": "Задачи по женской линии отца",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="AncestralPower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Необходимо сделать (e1)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Необходимо сделать (e1)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ancestral_powers",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сила рода",
                "verbose_name_plural": "Сила рода",
                "unique_together": {("category", "order_id")},
            },
        ),
    ]
