# Generated by Django 4.2.20 on 2025-03-14 16:43

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "matrix_fate_app",
            "0002_alter_birthtalent_options_alter_category_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AdjnaO6",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан AdjnaO6",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан AdjnaO6",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjna_o6",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан AdjnaO6",
                "verbose_name_plural": "Карта здоровья аркан AdjnaO6",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="AdjnaP6",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан AdjnaP6",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан AdjnaP6",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjna_p6",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан AdjnaP6",
                "verbose_name_plural": "Карта здоровья аркан AdjnaP6",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="AdjnaQ6",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан AdjnaQ6",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан AdjnaQ6",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjna_q6",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан AdjnaQ6",
                "verbose_name_plural": "Карта здоровья аркан AdjnaQ6",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="AnakhataO4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан AnakhataO4",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан AnakhataO4",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anakhata_o4",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан AnakhataO4",
                "verbose_name_plural": "Карта здоровья аркан AnakhataO4",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="AnakhataP4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан AnakhataP4",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан AnakhataP4",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anakhata_p4",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан AnakhataP4",
                "verbose_name_plural": "Карта здоровья аркан AnakhataP4",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="AnakhataQ4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан AnakhataQ4",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан AnakhataQ4",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anakhata_q4",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан AnakhataQ4",
                "verbose_name_plural": "Карта здоровья аркан AnakhataQ4",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="ManipuraO3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан ManipuraO3",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан ManipuraO3",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manipura_o3",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан ManipuraO3",
                "verbose_name_plural": "Карта здоровья аркан ManipuraO3",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="ManipuraP3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан ManipuraP3",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан ManipuraP3",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manipura_p3",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан ManipuraP3",
                "verbose_name_plural": "Карта здоровья аркан ManipuraP3",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="ManipuraQ3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан ManipuraQ3",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан ManipuraQ3",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manipura_q3",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан ManipuraQ3",
                "verbose_name_plural": "Карта здоровья аркан ManipuraQ3",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="MuladkharaO1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан Muladkhara1",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан Muladkhara1",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="muladkhara_o1",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан Muladkhara1",
                "verbose_name_plural": "Карта здоровья аркан Muladkhara1",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="MuladkharaP1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан MuladkharaP1",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан MuladkharaP1",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="muladkhara_p1",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан MuladkharaP1",
                "verbose_name_plural": "Карта здоровья аркан MuladkharaP1",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="MuladkharaQ1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан MuladkharaQ1",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан MuladkharaQ1",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="muladkhara_q1",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан MuladkharaQ1",
                "verbose_name_plural": "Карта здоровья аркан MuladkharaQ1",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="SahasraraO7",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан SahasraraO7",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан SahasraraO7",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sahasrara_o7",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан SahasraraO7",
                "verbose_name_plural": "Карта здоровья аркан SahasraraO7",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="SahasraraP7",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан SahasraraP7",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан SahasraraP7",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sahasrara_p7",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан SahasraraP7",
                "verbose_name_plural": "Карта здоровья аркан SahasraraP7",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="SahasraraQ7",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан SahasraraQ7",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан SahasraraQ7",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sahasrara_q7",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан SahasraraQ7",
                "verbose_name_plural": "Карта здоровья аркан SahasraraQ7",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="SvadkhistanaO2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан SvadkhistanaO2",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан SvadkhistanaO2",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="svadkhistana_o2",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан SvadkhistanaO2",
                "verbose_name_plural": "Карта здоровья аркан SvadkhistanaO2",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="SvadkhistanaP2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан SvadkhistanaP2",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан SvadkhistanaP2",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="svadkhistana_p2",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан SvadkhistanaP2",
                "verbose_name_plural": "Карта здоровья аркан SvadkhistanaP2",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="SvadkhistanaQ2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан SvadkhistanaQ2",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан SvadkhistanaQ2",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="svadkhistana_q2",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан SvadkhistanaQ2",
                "verbose_name_plural": "Карта здоровья аркан SvadkhistanaQ2",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="TotalO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан TotalO",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан TotalO", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="total_o",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан TotalO",
                "verbose_name_plural": "Карта здоровья аркан TotalO",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="TotalP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан TotalP",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан TotalP", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="total_p",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан TotalP",
                "verbose_name_plural": "Карта здоровья аркан TotalP",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="TotalQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан TotalQ",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан TotalQ", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="total_q",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан TotalQ",
                "verbose_name_plural": "Карта здоровья аркан TotalQ",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="VishudkhaO5",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан VishudkhaO5",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан VishudkhaO5",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vishudkha_o5",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан VishudkhaO5",
                "verbose_name_plural": "Карта здоровья аркан VishudkhaO5",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="VishudkhaP5",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан VishudkhaP5",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан VishudkhaP5",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vishudkha_p5",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан VishudkhaP5",
                "verbose_name_plural": "Карта здоровья аркан VishudkhaP5",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="VishudkhaQ5",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Карта здоровья аркан VishudkhaQ5",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Карта здоровья аркан VishudkhaQ5",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vishudkha_q5",
                        to="matrix_fate_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта здоровья аркан VishudkhaQ5",
                "verbose_name_plural": "Карта здоровья аркан VishudkhaQ5",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.DeleteModel(
            name="HealthMap",
        ),
    ]
