# Generated by Django 4.2.20 on 2025-03-16 18:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "matrix_fate_app",
            "0003_adjnao6_adjnap6_adjnaq6_anakhatao4_anakhatap4_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="moneygrowthtasks1",
            name="description",
            field=ckeditor.fields.RichTextField(
                help_text="Какие нужно проработать задачи, чтобы раскрыть денежный канал1(l)",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="moneygrowthtasks1",
            name="title",
            field=models.CharField(
                help_text="Какие нужно проработать задачи, чтобы раскрыть денежный канал1(l)",
                max_length=255,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="moneysources",
            name="description",
            field=ckeditor.fields.RichTextField(
                help_text="Что дает деньги (l)", verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="moneysources",
            name="title",
            field=models.CharField(
                help_text="Что дает деньги (l)", max_length=255, verbose_name="Название"
            ),
        ),
    ]
