# Generated by Django 4.2.20 on 2025-05-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "matrix_fate_app",
            "0006_alter_matrixfateprogram_options_adjnao6_marker_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="matrixfateprogram",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
