# Generated by Django 4.2.20 on 2025-03-15 18:41

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompatibilityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Название категории",
                        max_length=255,
                        verbose_name="Название категории",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Описание категории",
                        verbose_name="Описание категории",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(
                        default=False, verbose_name="Платная категория"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="WhyDidYouMeet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Для чего вы встретились (a)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Для чего вы встретились (a)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="why_did_you_meet",
                        to="compatibility_app.compatibilitycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Для чего вы встретились",
                "verbose_name_plural": "Для чего вы встретились",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="WhatTasksUnlockMoneyChannels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Какие нужно проработать задачи, чтобы раскрыть денежный канал: (j)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Какие нужно проработать задачи, чтобы раскрыть денежный канал: (j)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="what_tasks_unlock_money_channels_j",
                        to="compatibility_app.compatibilitycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Какие нужно проработать задачи, чтобы раскрыть денежный канал: (j)",
                "verbose_name_plural": "Какие нужно проработать задачи, чтобы раскрыть денежный канал: (j)",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="WhatRelationshipProblemsCanArise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Какие могут возникнуть проблемы в отношениях: (j)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Какие могут возникнуть проблемы в отношениях: (j)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="what_relationship_problems_can_arise_j",
                        to="compatibility_app.compatibilitycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Какие могут возникнуть проблемы в отношениях: (j)",
                "verbose_name_plural": "Какие могут возникнуть проблемы в отношениях: (j)",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="WhatGivesTribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Что дает деньги (k)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Что дает деньги (k)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="what_gives_tribute_k",
                        to="compatibility_app.compatibilitycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Что дает деньги (k)",
                "verbose_name_plural": "Что дает деньги (k)",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="WhatFillsTheVapor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="От чего наполняется пара (e)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="От чего наполняется пара (e)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="what_fills_the_vapor_e",
                        to="compatibility_app.compatibilitycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "От чего наполняется пара (e)",
                "verbose_name_plural": "От чего наполняется пара (e)",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="WhatBlocksMonetaryEnergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Что блокирует денежную энергию: (i1)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Что блокирует денежную энергию: (i1)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="what_blocks_monetary_energy_i1",
                        to="compatibility_app.compatibilitycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Что блокирует денежную энергию: (i1)",
                "verbose_name_plural": "Что блокирует денежную энергию: (i1)",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="TasksForCoupleArcana3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Задачи для пары (y)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Задачи для пары (y)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_for_couple_y",
                        to="compatibility_app.compatibilitycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задачи для пары (y)",
                "verbose_name_plural": "Задачи для пары (y)",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="TasksForCoupleArcana2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Задачи для пары (d)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Задачи для пары (d)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_for_couple_d",
                        to="compatibility_app.compatibilitycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задачи для пары (d)",
                "verbose_name_plural": "Задачи для пары (d)",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="TasksForCoupleArcana1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Задачи для пары (w)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Задачи для пары (w)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_for_couple_w",
                        to="compatibility_app.compatibilitycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задачи для пары (w)",
                "verbose_name_plural": "Задачи для пары (w)",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="CouplesTaskForSociety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Задача пары для социума (v)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Задача пары для социума (v)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="couples_task_for_society_v",
                        to="compatibility_app.compatibilitycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача пары для социума (v)",
                "verbose_name_plural": "Задача пары для социума (v)",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="CoupleResourcesArcana2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Ресурсы пары (c)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Ресурсы пары (c)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="couple_resources_c",
                        to="compatibility_app.compatibilitycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ресурсы пары (c)",
                "verbose_name_plural": "Ресурсы пары (c)",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="CoupleResourcesArcana1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Ресурсы пары (b)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Ресурсы пары (b)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="couple_resources_b",
                        to="compatibility_app.compatibilitycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ресурсы пары (b)",
                "verbose_name_plural": "Ресурсы пары (b)",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="CoupleRelations2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Отношения в паре (k)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Отношения в паре (k)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="couple_relations_k",
                        to="compatibility_app.compatibilitycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отношения в паре (k)",
                "verbose_name_plural": "Отношения в паре (k)",
                "unique_together": {("category", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="CoupleRelations1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Отношения в паре (d2)",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Отношения в паре (d2)", verbose_name="Описание"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="№ аркана",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="couple_relations_d2",
                        to="compatibility_app.compatibilitycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отношения в паре (d2)",
                "verbose_name_plural": "Отношения в паре (d2)",
                "unique_together": {("category", "order_id")},
            },
        ),
    ]
