# Generated by Django 4.2.20 on 2025-04-03 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compatibility_app", "0002_alter_whatblocksmonetaryenergy_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="couplerelations1",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="couplerelations2",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="coupleresourcesarcana1",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="coupleresourcesarcana2",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="couplestaskforsociety",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="tasksforcouplearcana1",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="tasksforcouplearcana2",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="tasksforcouplearcana3",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="whatblocksmonetaryenergy",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="whatfillsthevapor",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="whatgivestribute",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="whatrelationshipproblemscanarise",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="whattasksunlockmoneychannels",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AddField(
            model_name="whydidyoumeet",
            name="marker",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор ключа на схеме матрицы, например 'a'",
                max_length=10,
                null=True,
                verbose_name="Маркер",
            ),
        ),
        migrations.AlterField(
            model_name="couplerelations1",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="couplerelations2",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="coupleresourcesarcana1",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="coupleresourcesarcana2",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="couplestaskforsociety",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="tasksforcouplearcana1",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="tasksforcouplearcana2",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="tasksforcouplearcana3",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="whatblocksmonetaryenergy",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="whatfillsthevapor",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="whatgivestribute",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="whatrelationshipproblemscanarise",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="whattasksunlockmoneychannels",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
        migrations.AlterField(
            model_name="whydidyoumeet",
            name="order_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="№ аркана",
            ),
        ),
    ]
