# Generated by Django 4.2.20 on 2025-05-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compatibility_app", "0004_matrixcompatibilityprogram"),
    ]

    operations = [
        migrations.AddField(
            model_name="matrixcompatibilityprogram",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
